# Generated by Django 2.2.4 on 2020-03-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
